name: Run Spring Batch
on:
  workflow_dispatch: { }
jobs:
  run-batch:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'liberica'
        cache: maven
    - name: Build the jar file
      run: ./mvnw -V --no-transfer-progress clean package -DskipTests
    - name: Run the jar file
      run: |
        if [ -n "${{ secrets.MANAGEMENT_OTLP_LOGGING_ENDPOINT }}" ]; then
            export MANAGEMENT_OTLP_LOGGING_ENDPOINT="${{ secrets.MANAGEMENT_OTLP_LOGGING_ENDPOINT }}"
        fi
        if [ -n "${{ secrets.MANAGEMENT_OTLP_LOGGING_HEADERS_AUTHORIZATION }}" ]; then
            export MANAGEMENT_OTLP_LOGGING_HEADERS_AUTHORIZATION="${{ secrets.MANAGEMENT_OTLP_LOGGING_HEADERS_AUTHORIZATION }}"
        fi
        export MANAGEMENT_OPENTELEMETRY_RESOURCEATTRIBUTES_GITHUB_REPOSITORY=${GITHUB_REPOSITORY}
        export MANAGEMENT_OPENTELEMETRY_RESOURCEATTRIBUTES_GITHUB_SHA=${GITHUB_SHA}
        export MANAGEMENT_OPENTELEMETRY_RESOURCEATTRIBUTES_GITHUB_RUN_NUMBER=${GITHUB_RUN_NUMBER}
        java -jar target/*.jar
